version: "3.8"
services:
  web:
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - SESSION_SECRET=registroconstructores
    build:
      context: ./app
      target: development
    restart: always
    networks:
      registroconstructores-network:
        aliases:
          - app
    depends_on:
      - backoffice
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    
  backoffice:
    environment:
      - DB_URI=mongodb://mongo:27017/registroconstructores
      - JWT_SECRET=registroconstructores-secret-shhhhhh
    build:
      context: ./backoffice
      target: development
    restart: always
    ports:
      - 3030:3030
    networks:
      registroconstructores-network:
        aliases:
          - backoffice
    depends_on:
      - mongo
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
  nginx: 
    build: ./nginx
    ports:
      - 8082:80
    networks:
      registroconstructores-network:
        aliases:
          - nginx
    depends_on:
      - web
  mongo:
    image: mongo:4.2.5
    networks:
      registroconstructores-network:
        aliases:
          - mongo
    restart: always
    volumes:
      - datadb:/data/db
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  datadb:

networks:
  registroconstructores-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
