version: "3.8"
services:
  web:
    build:
      context: ./app
      target: development
    restart: always
    ports:
      - 3000:3000
    networks:
      fichap-network:
        aliases:
          - app
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
  backoffice:
    build:
      context: ./backoffice
      target: development
    restart: always
    ports:
      - 3030:3030
    networks:
      fichap-network:
        aliases:
          - backoffice
    depends_on:
      - mongo
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  mongo:
    image: mongo:4.2.5
    networks:
      fichap-network:
        aliases:
          - mongo
    ports:
      - 27018:27017
    restart: always
    volumes:
      - datadb:/data/db
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  datadb:

networks:
  fichap-network:
    driver: bridge
